version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: DB-service__Postgresql__for-AIStudyTracker
    ports:
      - '${DB_PORT}:5432'
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      POSTGRESQL_USERNAME: ${DB_USERNAME}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_DATABASE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin-for-AIStudyTracker
    ports:
      - '${DB_ADMIN_PORT}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ADMIN_PASSWORD}
    restart: unless-stopped
    depends_on:
      - postgres
